apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: iep-investment-fund
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  # Keep the PV and its data when the PVC is deleted accidentally.
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /tmp/iep-investment-fund/mysql
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: iep-investment-fund
spec:
  storageClassName: ""
  volumeName: mysql-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
